Resolves Spelling / Grammar on the menu interactions page
smartdevicelink/sdl_overview_guides pull request #63
Opened 2020-09-14 15:48 UTC by jordynmackool

Fixes issue #62

2020-09-16 18:47 UTC, theresalech requested changes

2020-09-16 18:47 UTC, theresalech commented on docs/Best Practices/Menu Interactions/index.md
> +		- Present each result on on its own screen via `Show` and announce it with a pure voice alert via`Speak`.
```suggestion
		- Present each result on its own screen via `Show` and announce it with a pure voice alert via `Speak`.  
```

2020-09-16 18:47 UTC, theresalech commented on docs/Best Practices/Menu Interactions/index.md
> +       - Announce the availability of `Skip`hard button on the steering wheel for easy navigation.
```suggestion
       - Announce the availability of `Skip` hard button on the steering wheel for easy navigation.
```

2020-09-22 13:02 UTC, theresalech requested changes
I found a few more minor typos that can be resolved in this PR.

2020-09-22 13:02 UTC, theresalech commented on docs/Best Practices/Menu Interactions/index.md
>         - Softbuttons & Voice commands
```suggestion
       - Softbuttons & voice commands
```

2020-09-22 13:26 UTC, jordynmackool commented
Committed changes based on review suggestions. Ready for re-review @theresalech.

2020-09-22 15:41 UTC, theresalech approved these changes

2020-09-22 19:46 UTC, merged